name: Build docs

on:
  push:
  pull_request:

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          pip install -U -r requirements.txt
      - name: Sphinx build
        run: |
          echo "::add-matcher::.github/matchers/sphinx.json"
          make -C docs/ html SPHINXOPTS="${SPHINXOPTS}"
          echo "::remove-matcher owner=sphinx::"
        env:
          SPHINXOPTS: -n -W -a --keep-going
      - name: Upload docs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: docs/_build/**/html

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          pip install -U -r requirements.txt
      - name: Sphinx linkcheck
        run: |
          make -C docs/ linkcheck SPHINXOPTS="${SPHINXOPTS}"
        env:
          SPHINXOPTS: -n -W -a --keep-going
      - name: Sphinx linkcheck collect
        if: always()
        run: |
          echo "::add-matcher::.github/matchers/sphinx-linkcheck.json"
          echo "::add-matcher::.github/matchers/sphinx-linkcheck-warn.json"
          sed 's@^@docs/@' docs/_build/linkcheck/output.txt
          echo "::remove-matcher owner=sphinx::"
          echo "::remove-matcher owner=sphinx-warn::"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Linkcheck report
          path: docs/_build/**/linkcheck/output.txt
