name: Build docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      SPHINXOPTS: --color -q -E --keep-going -W

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          pip install -U -r requirements.txt
      - run: make -C docs/ html SPHINXOPTS="${SPHINXOPTS}"
      - name: Upload docs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: translated-docs
          path: docs/_build/**/html
