name: Update translations

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: {}

jobs:
  archive:
    name: Update translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          pip install -U -r requirements.txt

      - name: Update translations
        run: make -C docs update-po

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: "random"
          commit-message: (Automated) Update translations
          title: "(Automated) Update translations"
          body: Update translations
          delete-branch: true
          sign-commits: true
          draft: always-true
